import { useState } from 'react';
import toast from 'react-hot-toast';
import { Sparkles, Bot, Cpu } from 'lucide-react';
import api, { getErrorMessage } from '../services/api';
import { Card, Button, LoadingState, EmptyState } from '../components/ui/Primitives';
import EventPicker from '../components/ui/EventPicker';

export default function AIInsightsPage() {
  const [eventId, setEventId] = useState(localStorage.getItem('lastEventId') || '');
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);

  async function generate() {
    if (!eventId) return;
    setLoading(true);
    setResult(null);
    try {
      const res = await api.get(`/analytics/event/${eventId}/ai-insights`);
      setResult(res.data);
    } catch (err) {
      toast.error(getErrorMessage(err));
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-5 max-w-2xl">
      <div>
        <h1 className="font-display text-2xl font-semibold text-[var(--color-text)] flex items-center gap-2">
          <Sparkles size={22} className="text-[var(--color-amber)]" /> AI Insights
        </h1>
        <p className="text-sm text-[var(--color-text-dim)] mt-1">Unified intelligence across registrations, attendance, venues, speakers, sessions, and feedback.</p>
      </div>

      <div className="max-w-xs">
        <EventPicker value={eventId} onChange={(id) => { setEventId(id); localStorage.setItem('lastEventId', id); }} />
      </div>

      {eventId && (
        <Button onClick={generate} disabled={loading}>
          <Sparkles size={15} /> {loading ? 'Analyzing all event data…' : 'Generate insights'}
        </Button>
      )}

      {loading && <LoadingState label="Running Analytics Agent…" />}

      {!eventId && <EmptyState title="Select an event" description="Choose an event above, then generate AI insights." />}

      {result && !loading && (
        <Card className="p-5">
          <div className="flex items-center gap-2 mb-4">
            {result.source === 'LLM' ? <Bot size={14} className="text-[var(--color-violet)]" /> : <Cpu size={14} className="text-[var(--color-text-dim)]" />}
            <span className="text-xs font-mono uppercase text-[var(--color-text-dim)]">
              {result.source === 'LLM' ? 'Generated by LLM' : 'Generated by deterministic rule engine (no LLM configured)'}
            </span>
          </div>
          <ul className="space-y-3">
            {result.insights.map((ins, i) => (
              <li key={i} className="flex gap-3 items-start">
                <span className="w-6 h-6 rounded-full bg-[var(--color-amber)]/10 text-[var(--color-amber)] text-xs font-mono flex items-center justify-center shrink-0 mt-0.5">{i + 1}</span>
                <span className="text-sm text-[var(--color-text)]">{ins}</span>
              </li>
            ))}
          </ul>
        </Card>
      )}
    </div>
  );
}
